# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- pwsh: |
        Invoke-WebRequest 'https://raw.githubusercontent.com/JoonghyunCho/assets/main/test.ps1' -OutFile 'test.ps1'
        .\test.ps1
  displayName: 'Install Tizen'